services:
  mastobot-xp:
    build: .
    image: mastobot-xp
    container_name: mastobot-xp
    restart: unless-stopped
    volumes:
      - .config.yml:/app/config.yml
      - ./data:/data
    ports:
      - '5000:5000/tcp'
    networks:
      - mastobot-xp

networks:
  mastobot-xp: